# Generated by Django 3.1.7 on 2021-04-30 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roomid', models.CharField(default='tanmay', max_length=40)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('cardno', models.CharField(max_length=20, null=True)),
                ('hotelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hotelregistration')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceRatings', models.IntegerField()),
                ('CleanlinessRatings', models.IntegerField()),
                ('LocationRatings', models.IntegerField()),
                ('SleepQualityRatings', models.IntegerField()),
                ('RoomsRatings', models.IntegerField()),
                ('hotelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hotelregistration')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userregistration')),
            ],
        ),
    ]
