# Generated by Django 3.1.7 on 2021-04-30 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=20)),
                ('statename', models.CharField(default='Gujarat', max_length=20)),
                ('countryname', models.CharField(default='India', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRegistration',
            fields=[
                ('hotelid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('hotelname', models.CharField(max_length=50)),
                ('hotelpassword', models.CharField(max_length=40)),
                ('hotelmobileno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('userid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('userpassword', models.CharField(max_length=40)),
                ('usermobileno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoteladdress', models.CharField(max_length=100)),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.city')),
                ('hotelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hotelregistration')),
            ],
        ),
    ]
