# Generated by Django 3.1.7 on 2021-04-30 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('roomid', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('roomno', models.IntegerField()),
                ('hotelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hotelregistration')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=10)),
                ('roomdescription', models.CharField(max_length=100)),
                ('roombeds', models.IntegerField()),
                ('roomrent', models.CharField(max_length=6)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelroom')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelimg', models.ImageField(blank=True, null=True, upload_to='hotelimage')),
                ('hotelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hotelregistration')),
            ],
        ),
    ]
