# Generated by Django 3.1.7 on 2021-04-30 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomimg', models.ImageField(blank=True, null=True, upload_to='roomimage')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelroom')),
            ],
        ),
    ]
